import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import AuthProvider from "./services/AuthProvider";
import Navbar from "./components/Navbar";
import { NextUIProvider } from "@nextui-org/react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full max-w-7xl mx-auto`}
      >
        <NextUIProvider>
          <AuthProvider>
            <Navbar />
            {children}
          </AuthProvider>
        </NextUIProvider>
        <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
}
